### ISSUE TITLE
Error: spawn afplay ENOENT

### ISSUE THREAD

**Issue by f4th4n** [niftylettuce/pomodoro-timer#9]
How to get assets/start.wav?

`test ------------------------- 0% 0 splaying=>/home/joe/tmp/node_modules/pomodoro-timer/assets/start.wav
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn afplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)`

**Comment by Tallestthomas** [comment]
Which operating system is this on?
Are you installing the package globally?

**Comment by f4th4n** [comment]
OS: Ubuntu 18

I'm installing globally
